name: library-access
dependencies:
- anaconda::beautifulsoup4=4.6.0
- anaconda::ipython=5.3.0
- anaconda::pandas=0.20.1
- anaconda::pep8=1.7.0
- anaconda::pip=9.0.1
- anaconda::python=3.6.1
- anaconda::r-base=3.4.1
- anaconda::requests=2.14.2
- anaconda::spyder=3.1.4
- anaconda::sqlalchemy=1.1.9
- anaconda::sqlite=3.13.0
- anaconda::yaml=0.1.6
- pip:
  - backoff==1.4.3
  - ratelimit==1.4.1
  - lxml==3.7.3
